## 线性代数

In [10]:
import torch

### 标量

In [12]:
# 一维数组中只有一个元素，就是一个标量
x = torch.tensor([2.0])
y = torch.tensor([3.0])
x + y, x - y, x * y, x / y, x ** y

(tensor([5.]), tensor([-1.]), tensor([6.]), tensor([0.6667]), tensor([8.]))

### 向量

In [42]:
# 向量是标量值组成的列表，一维数组有多个元素
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [15]:
x1 = torch.tensor([0, 1, 2, 3, 4, 5])
x1

tensor([0, 1, 2, 3, 4, 5])

In [16]:
# 访问元素
x[3]

tensor(3)

In [17]:
# 张量的长度
len(x)

12

In [18]:
# 张量的形状
x.shape

torch.Size([12])

### 矩阵

In [20]:
A = torch.arange(20).reshape(4, 5)
A

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [21]:
# 矩阵的转置 行列互换
A.T

tensor([[ 0,  5, 10, 15],
        [ 1,  6, 11, 16],
        [ 2,  7, 12, 17],
        [ 3,  8, 13, 18],
        [ 4,  9, 14, 19]])

In [23]:
# 对称矩阵的转置是自己 （沿主轴堆成）
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B, B.T, B == B.T

(tensor([[1, 2, 3],
         [2, 0, 4],
         [3, 4, 5]]),
 tensor([[1, 2, 3],
         [2, 0, 4],
         [3, 4, 5]]),
 tensor([[True, True, True],
         [True, True, True],
         [True, True, True]]))

### 矩阵相关的运算

In [27]:
# A + B
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone() # 重新分配了一个新的内存拷贝给B，A和B无关，深拷贝
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [39]:
# 矩阵元素相乘， 哈达玛积 （只是元素相乘，不是矩阵乘法）
# 数乘
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [46]:
# 点积是相同位置的按元素累积的和
y = torch.ones(4, dtype=torch.float32)
x = torch.arange(4, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [49]:
# 矩阵和向量相乘
# mv 代表 matrix vector
A, x, A.shape, x.shape, torch.mv(A, x)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([0., 1., 2., 3.]),
 torch.Size([5, 4]),
 torch.Size([4]),
 tensor([ 14.,  38.,  62.,  86., 110.]))

In [53]:
# 矩阵的乘法（真正的矩阵乘法）
# mm 代表 matrix matrix
C = torch.ones(4, 3)
C, A, C.shape, A.shape, torch.mm(A, C)

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 torch.Size([4, 3]),
 torch.Size([5, 4]),
 tensor([[ 6.,  6.,  6.],
         [22., 22., 22.],
         [38., 38., 38.],
         [54., 54., 54.],
         [70., 70., 70.]]))

### 更多维度

#### Note: 向量是标量的扩展，矩阵是向量的扩展，三维是矩阵的扩展... 可以表示更高的维度

In [25]:
X = torch.arange(24).reshape(2, 3, 4) # 深度2. 此处主要还是看矩阵嵌套的层次，24 = 2 * 3 * 4
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

 ### 运算符

In [27]:
# 计算元素的求和
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [3]:
# 求和可以表示任意形状的张量
A = torch.arange(40).reshape(2, 5, 4)
A, A.shape, A.sum()

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11],
          [12, 13, 14, 15],
          [16, 17, 18, 19]],
 
         [[20, 21, 22, 23],
          [24, 25, 26, 27],
          [28, 29, 30, 31],
          [32, 33, 34, 35],
          [36, 37, 38, 39]]]),
 torch.Size([2, 5, 4]),
 tensor(780))

In [33]:
# 指定轴进行求和
B

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [31]:
# axis = 0 按照行进行操作
B_sum_axis0 = B.sum(axis=0)
B_sum_axis0, B_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [32]:
# axis = 1 按照列进行操作
B_sum_axis1 = B.sum(axis=1)
B_sum_axis1, B_sum_axis1.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

In [34]:
# 求均值
B.mean(), B.sum() / B.numel()

(tensor(9.5000), tensor(9.5000))

In [36]:
B.mean(axis=0), B.sum(axis=0) / B.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

#### Note: 按照某个维度axis 进行求和，维度会下降，从原来二维变为一维，从原来三维变为二维

#### keepdims=True， 保持维度，可以进行广播机制（广播机制的维度要一致）

In [37]:
sum_B = B.sum(axis=1, keepdims=True)
sum_B

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [38]:
B / sum_B

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])