## 自动求导

### 假设对函数 y=2x^Tx 关于列向量x 求导

In [2]:
import torch

In [3]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [5]:
# 计算y关于x的梯度之前，需要一个地方来存储梯度
x.requires_grad_(True)
x.grad

In [6]:
# 计算y
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [7]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [8]:
x.grad == 4 * x

tensor([True, True, True, True])

In [10]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])