In [44]:
import torch

In [14]:
print('Hello Lesenelir')

Hello Lesenelir


### 张量表示数值组成的数组

#### Note：张量是多元数组。张量可以是任意维度，常见的是一维张量

In [10]:
# torch 中的一维数组
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
x.shape # shape可访问张量的形状

torch.Size([12])

In [29]:
x.numel() # 元素的总数 标量

12

In [32]:
# 转变为torch 中的二维数组
X = x.reshape(3, 4) # 改变张量的形状，但是不改变元素的数量和值
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

### 使用全0、全1、其他常量

In [34]:
torch.zeros((2, 3, 4)) # 三维数组

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [75]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [76]:
torch.zeros(1) # 一维数组

tensor([0.])

In [79]:
torch.zeros((2, 3)) # 二维数组

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [80]:
torch.randn(3, 4) # 随机变量

tensor([[-0.6939,  0.2754, -0.7231, -0.1856],
        [ 1.2013, -1.0580,  0.0280,  0.3054],
        [-0.2268,  0.6813, -0.0318,  1.3933]])

### 通过列表来确定张量

##### Note: 矩阵是二维张量，torch.tensor(列表数组，可以是一维、二维、三维)

In [37]:
torch.tensor([[2, 1, 4, 4], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 4],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [38]:
torch.tensor([[2, 1, 4, 4], [1, 2, 3, 4], [4, 3, 2, 1]]).shape

torch.Size([3, 4])

In [39]:
torch.tensor([[[2, 1, 4, 4], [1, 2, 3, 4], [4, 3, 2, 1]]]) # 三维 含有深度

tensor([[[2, 1, 4, 4],
         [1, 2, 3, 4],
         [4, 3, 2, 1]]])

In [40]:
torch.tensor([[[2, 1, 4, 4], [1, 2, 3, 4], [4, 3, 2, 1]]]).shape

torch.Size([1, 3, 4])

### 按元素进行算数运算

In [42]:
x = torch.tensor([1.0, 2, 4, 8]) # 浮点数组
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

### 多个张量拼接

In [52]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
# 连接X张量和Y张量
# dim = 0 代表按照行拼接
# dim = 1 代表按照列拼接
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [53]:
X.sum() # 对张量中的所有元素进行求和会产生一个只有一个元素的张量

tensor(66.)

### 即使形状不同，仍可以通过调用广播机制 broadcasting mechanism 来执行元素操作

#### Note: 广播机制 会给两个形状不同的张量进行元素的元素，（前提：两个张量的维数要一致）

In [54]:
# a 和 b 的维度都是2
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [55]:
# 执行a + b 的操作，a会变为3*2 , b会变为3*2
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

### 元素的访问

In [56]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [57]:
X[-1] # 最后一后

tensor([ 8.,  9., 10., 11.])

In [58]:
X[1: 3] # 第一行和第二行

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [60]:
X[1:3,0:2] # 第一行和第二行中的第一列和第二列

tensor([[4., 5.],
        [8., 9.]])

### 元素的写入

In [61]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [63]:
X[1,2] = 9 # 标识 第一行第二列元素值为9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [65]:
X[0:2, :] = 12 # 区域赋值
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

### id 取内存地址 唯一标识

In [66]:
address = id(X)
address

140192991248112

### 转换为NumPy张量

In [68]:
A = X.numpy()
B = torch.tensor(A)
A, type(A), B, type(B)

(array([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]], dtype=float32),
 numpy.ndarray,
 tensor([[12., 12., 12., 12.],
         [12., 12., 12., 12.],
         [ 8.,  9., 10., 11.]]),
 torch.Tensor)

### 大小为1的张量转换为Python标量

In [78]:
a = torch.tensor([3.6])
a, a.item(), float(a), int(a)

(tensor([3.6000]), 3.5999999046325684, 3.5999999046325684, 3)