## 数据预处理

In [22]:
import os
import pandas as pd
import torch

### 创建一个人工数据集

In [15]:
os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms, Alley, Price\n') # 列名
    f.write('NA,Pave,127500\n')
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

### 读取CSV文件

#### Note： 一般读取csv文件都是使用pandas库

In [27]:
data = pd.read_csv(data_file)
data

NumRooms  Alley   Price
0       NaN   Pave  127500
1       2.0    NaN  106000
2       4.0    NaN  178100
3       NaN    NaN  140000

### 处理缺失数据，进行插值

In [17]:
# iloc => index location
# inputs为所有行的前两列，output是所有行的第三列
# data是一个DataFrame，读取DataFrame是通过iloc来处理
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2] 
inputs, outputs

(   NumRooms  Alley
 0       NaN   Pave
 1       2.0    NaN
 2       4.0    NaN
 3       NaN    NaN,
 0    127500
 1    106000
 2    178100
 3    140000
 Name:  Price, dtype: int64)

In [18]:
# 处理数值域
inputs = inputs.fillna(inputs.mean()) # fillna 填充nan not a number 的值为 inputs.means()均值
inputs

NumRooms  Alley
0       3.0   Pave
1       2.0    NaN
2       4.0    NaN
3       3.0    NaN

In [19]:
# 对于非数值域（类别值、离散值）， 将NAN当作一个类别
# 缺失值作为一类，并将其作为数值
inputs = pd.get_dummies(inputs, dummy_na=True)
inputs

NumRooms   Alley_Pave   Alley_nan
0       3.0            1           0
1       2.0            0           1
2       4.0            0           1
3       3.0            0           1

In [20]:
inputs.values # 二维数组

array([[3., 1., 0.],
       [2., 0., 1.],
       [4., 0., 1.],
       [3., 0., 1.]])

In [21]:
outputs.values

array([127500, 106000, 178100, 140000])

### 将预处理数据作为张量

In [24]:
# X是一个二维数组张量，y是一个一维数组张量
X, y = torch.tensor(inputs.values), torch.tensor(outputs.values)
X, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

#### Note： 对于深度学习一般用32位浮点数，64位浮点数计算较慢

In [25]:
X.shape # 二维数组，4行3列

torch.Size([4, 3])