### 使用深度学习框架 torch 来实现 线性回归模型

In [13]:
import numpy as np
import torch
from torch.utils import data
from d2l import torch as d2l

### 生成数据集

In [14]:
# 生成真实数据集
true_w = torch.tensor([2, -3.4]) # 真实w
true_b = 4.2                     # 真实b
features, labels = d2l.synthetic_data(true_w, true_b, 1000)
features, labels[0]

(tensor([[ 0.1591, -0.5336],
         [-0.5213, -0.0229],
         [ 0.4987,  0.5379],
         ...,
         [-0.0769, -0.9922],
         [ 1.3177,  2.0280],
         [ 0.0570,  0.1006]]),
 tensor([6.3254]))

### 读取数据

In [20]:
# 将features 和 labels 作为API的参数传递，指定batch size
# 布尔值is_train表示是否希望数据迭代器对象在每个迭代周期内打乱数据
def load_array(data_arrays, batch_size, is_train=True):
    """构造一个PyTorch数据迭代器"""
    dataset = data.TensorDataset(*data_arrays)
    return data.DataLoader(dataset, batch_size, shuffle=is_train)

batch_size = 10
data_iter = load_array((features, labels), batch_size)

next(iter(data_iter)) # next从迭代器中获取第一项

[tensor([[ 0.4920, -0.3733],
         [-0.2853,  0.3326],
         [-1.2259, -1.3245],
         [-0.3651,  0.2436],
         [-0.5251, -2.0397],
         [ 0.7511,  0.1285],
         [ 0.7728,  0.6192],
         [ 0.4369,  1.8632],
         [-0.5188,  0.0574],
         [-0.9748, -0.3369]]),
 tensor([[ 6.4440],
         [ 2.5130],
         [ 6.2304],
         [ 2.6365],
         [10.0973],
         [ 5.2790],
         [ 3.6416],
         [-1.2552],
         [ 2.9510],
         [ 3.3895]])]

### 模型的定义

In [7]:
# nn 是 neural network
from torch import nn

net = nn.Sequential(nn.Linear(2, 1)) # 输入的维度是2，输出的维度是1

### 初始化模型参数

In [8]:
# net 只有一层 layer

net[0].weight.data.normal_(0, 0.01)
net[0].bias.data.fill_(0)

tensor([0.])

### 定义损失函数

In [9]:
# 均方误差 是 MSELoss
# 平方
loss = nn.MSELoss()

### 定义梯度下降的优化算法：SGD

In [11]:
# 随机梯度下降法
trainer = torch.optim.SGD(net.parameters(), lr=0.03)

### 训练过程

In [12]:
num_epochs = 3
for epoch in range(num_epochs):
    # 每一个迭代周期，遍历完一遍所有的train_data
    for X, y in data_iter: # 数据
        l = loss(net(X) ,y) # net(X)预测值， 真实值y，计算损失l
        trainer.zero_grad() # 优化器梯度清零
        l.backward() # 计算 反向传播计算梯度
        trainer.step() # 调用优化器，模型的一次更新 SGD
    l = loss(net(features), labels) # 扫完一遍数据之后，将loss计算一次并打印
    print(f'epoch {epoch + 1}, loss {l:f}')

epoch 1, loss 0.000168
epoch 2, loss 0.000102
epoch 3, loss 0.000101
